version: "3.7"
services:
  alert_bot:
    image: alert_bot
    container_name: alert_bot
    restart: always
    ports:
      - 4000:4000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - monitoring
networks:
  monitoring: