
TOKEN="n7d9lmC2soRW7-PhxfYhrR1ZXqRQBcrQCKIil8gUa2UqaOmlJ04sgrURIZ2Cy6dBQuWSb1P1HUSgQlmwffWcfQ=="
ADDRESS="http://192.168.1.100:9999/api/v2"
ORGID="05a1977d941a7000" #iot-org
USERID="05a1977d23da7000" #admin
BUCKETNAME="iot-demo"
TASKNAME="HumidityAlert"
TASKDESC="Monitoring_humidity"

TIMEINTERVAL="1m"
START="1m"
TIMEAGGREGATE="1m"
CRITICVAL="55"
TYPETHRESHOLD="greater"

MEASUREMENT="humidity"
DEVICE="RoomWeather"


node createAlert.js ${TOKEN} ${ADDRESS} ${ORGID} ${USERID} ${BUCKETNAME} ${TASKNAME} ${TASKDESC} ${TIMEINTERVAL} ${START} ${MEASUREMENT} ${TIMEAGGREGATE} ${CRITICVAL} ${TYPETHRESHOLD} ${DEVICE}