version: "3.7"
services:
  grafana:
    image: alarm_bot
    container_name: alarm_bot
    restart: always
    ports:
      - 4000:4000
    networks:
      - monitoring
    env_file:
      - .env
networks:
  monitoring: